# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2020

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives/
  # Tags: /tags/
  # Categories: /categories/
  About: /about/

# ===========================================
# Theme Settings
# ===========================================
# color: default | mint green | cobalt blue | hot pink | dark violet
color: default

# default page mode: default | archives
mode: default

toc: true

# jQuery fancybox
fancybox: true

# LaTeX support (via MathJax)
latex: true

copyright:
  enable: true
  # https://creativecommons.org/
  license: '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>'

reward:
  enable: true
  qrCode:
    wechat: /image/reward/微信赞赏码.jpeg
    alipay:

# ===========================================
# Social links Settings
# ===========================================
social:
  email: 956318206@qq.com
  stack-overflow:
  twitter:
  facebook:
  linkedin:
  google:
  github: https://github.com/Wangzhike
  weibo:
  zhihu: http://www.zhihu.com/people/qiuyu_mac
  douban:
  pocket:
  tumblr:
  instagram:

# ===========================================
# Third Party Services Settings
# ===========================================

# LeanCloud
leancloud:
  app_id: Njx4Ne9mGBb7pcb9o7LnU7pS-gzGzoHsz
  app_key: PeEBRXFsg7dSNhNWG7Cc8jGS

# Baidu Analytics
baidu_analytics:
# Baidu Verification
baidu_verification:

# Google Analytics
google_analytics:
# Google Verification
google_verification:

# Disqus
disqus_shortname:

#Changyan
changyan:
  appid:
  appkey:

#LiveRe
livere_datauid:

# Gitalk
# Demo: https://gitalk.github.io
# https://github.com/gitalk/gitalk
gitalk:
  enable: false
  github_id: GitHub repo owner
  repo: GitHub repo
  client_id: GitHub Application Client ID
  client_secret: GitHub Application Client Secret
  admin_user: GitHub repo owner and collaborators, only these guys can initialize github issues
  distraction_free_mode: true # Facebook-like distraction free mode
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en, es-ES, fr, ru, zh-CN, zh-TW
  language:

# utterances
# Docs: https://utteranc.es/
# Tips: Make sure you have installed [utterances app](https://github.com/apps/utterances) in your repo
utterances:
  enable: true
  repo: Wangzhike/utterance_comment # Repository
  issueTerm: title  # Blog post ↔️ issue mapping: pathname | url | title | og:title
  theme: github-light # Theme: github-light | github-dark | github-dark-orange | icy-dark | dark-blue | photon-dark
  label: utterances # Issue label

# ===========================================
# Version
# ===========================================
version: 2.11.0